// ------------------------------------
// SVG Canvas
// ------------------------------------

export const WIDTH = 1200;

export const HEIGHT = 900;


// ------------------------------------
// Safe Text
// ------------------------------------

export function safe(text) {

    if (text === undefined || text === null)
        return "";

    return String(text)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");

}


// ------------------------------------
// SVG Header
// ------------------------------------

export function header(
    title = "Syllogism Diagram"
) {

return `

<svg
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink"
width="${WIDTH}"
height="${HEIGHT}"
viewBox="0 0 ${WIDTH} ${HEIGHT}"
preserveAspectRatio="xMidYMid meet">

<defs>

<linearGradient
id="bg"
x1="0%"
y1="0%"
x2="0%"
y2="100%">

<stop
offset="0%"
stop-color="#F8FAFC"/>

<stop
offset="100%"
stop-color="#E2E8F0"/>

</linearGradient>

<radialGradient
id="circleGlow">

<stop
offset="0%"
stop-color="white"
stop-opacity="0.45"/>

<stop
offset="100%"
stop-color="white"
stop-opacity="0"/>

</radialGradient>

<filter
id="shadow"
x="-30%"
y="-30%"
width="160%"
height="160%">

<feDropShadow
dx="0"
dy="6"
stdDeviation="8"
flood-color="#64748B"
flood-opacity="0.30"/>

</filter>

<filter
id="softShadow"
x="-40%"
y="-40%"
width="180%"
height="180%">

<feDropShadow
dx="0"
dy="3"
stdDeviation="4"
flood-color="#94A3B8"
flood-opacity="0.18"/>

</filter>

</defs>

<rect
width="100%"
height="100%"
fill="url(#bg)"/>

<rect
x="30"
y="30"
width="${WIDTH-60}"
height="${HEIGHT-60}"
rx="28"
fill="white"
stroke="#CBD5E1"
stroke-width="2"
filter="url(#shadow)"/>

<text
x="${WIDTH/2}"
y="72"
text-anchor="middle"
font-size="38"
font-family="Arial"
font-weight="700"
fill="#0F172A">

${safe(title)}

</text>

<text
x="${WIDTH/2}"
y="108"
text-anchor="middle"
font-size="18"
font-family="Arial"
fill="#64748B">

Venn / Euler Diagram

</text>

`;

}


// ------------------------------------
// Footer
// ------------------------------------

export function footer() {

return `

<line
x1="80"
y1="${HEIGHT-72}"
x2="${WIDTH-80}"
y2="${HEIGHT-72}"
stroke="#CBD5E1"
stroke-width="2"/>

<text
x="${WIDTH/2}"
y="${HEIGHT-36}"
text-anchor="middle"
font-size="18"
font-family="Arial"
fill="#64748B">

Generated by BIJUSH Quiz Engine

</text>

</svg>

`;

}


// ------------------------------------
// SVG Builder
// ------------------------------------

export function buildSVG(
    title,
    content
){

    return (

        header(title)

        +

        content

        +

        footer()

    );

}
